# Generated by Django 3.2 on 2021-06-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('mailid', models.CharField(default='', max_length=50)),
                ('phoneNumber', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
