# Generated by Django 3.2 on 2021-06-04 16:18

from django.db import migrations, models
import usermanagement.validations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_createuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='fullname',
            field=models.CharField(default='', max_length=100, validators=[usermanagement.validations.checkNull]),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='mailid',
            field=models.CharField(default='', max_length=50, validators=[usermanagement.validations.emailValidation]),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='phoneNumber',
            field=models.CharField(default='', max_length=10, validators=[usermanagement.validations.phoneNumberValidation]),
        ),
    ]
