# Generated by Django 3.2 on 2021-06-04 17:25

from django.db import migrations, models
import usermanagement.validations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_auto_20210604_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='mailid',
            field=models.CharField(default='', max_length=50, unique=True, validators=[usermanagement.validations.emailValidation]),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='phoneNumber',
            field=models.CharField(default='', max_length=10, unique=True, validators=[usermanagement.validations.phoneNumberValidation]),
        ),
    ]
